plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

repositories {
	// Loom ajoute automatiquement les dépôts Maven nécessaires (Minecraft, Fabric).
}

loom {
	mods {
		"ecransansfeu" {
			sourceSet sourceSets.main
		}
	}
}

dependencies {
	// Les versions se règlent dans gradle.properties
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API : utilisée pour les touches et l'événement de tick client.
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
	it.options.encoding = "UTF-8"
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}
